name: stocks
description: An iOS app that list your stocks and their performance.

publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  provider: ^6.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/images/disney.jpg
    - assets/images/tesla.jpg
    - assets/images/default.jpg

flutter_icons:
  ios: true
  image_path: "assets/icon/launcher_icon.png"
